(() => {
  const KEY = "skaicloud.commerce_marketplace.products";
  const empty = [];
  const state = { products: [], selectedId: null, images: [], loading: true };
  const $ = (id) => document.getElementById(id);
  const esc = (value) => String(value ?? "").replace(/[&<>\"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[char]));
  function loadLocal() { try { return JSON.parse(localStorage.getItem(KEY) || "[]"); } catch { return empty; } }
  async function load() { if (!window.SkaiCloudModuleBridge) return loadLocal(); const result = await window.SkaiCloudModuleBridge.list("products"); return (result.records || []).map((record) => ({ ...record.data, id: record.recordKey, status: record.published ? "published" : "draft" })); }
  function imageSrc(value) { return typeof value === "string" ? value : value?.url || value?.src || "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='300'%3E%3Crect width='100%25' height='100%25' fill='%23e2e8f0'/%3E%3C/svg%3E"; }
  function image(product) { return imageSrc(product.images?.[0]); }
  async function saveProduct(product, current) { if (!window.SkaiCloudModuleBridge) { const next = current ? state.products.map((item) => item.id === current.id ? product : item) : [product, ...state.products]; localStorage.setItem(KEY, JSON.stringify(next)); return; } const data = { ...product }; delete data.id; delete data.status; current ? await window.SkaiCloudModuleBridge.update("products", current.id, data, product.status === "published") : await window.SkaiCloudModuleBridge.create("products", product.id, data, product.status === "published"); }
  function saved() { $("save-state").textContent = "Saved"; setTimeout(() => { $("save-state").textContent = "Ready"; }, 1200); }
  function formatPrice(value) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value) || 0); }
  function toast(message) { $("toast").textContent = message; $("toast").classList.add("show"); setTimeout(() => $("toast").classList.remove("show"), 2200); }
  function render() {
    const query = $("product-search").value.toLowerCase(); const filter = $("status-filter").value;
    const items = state.products.filter((product) => (filter === "all" || (filter === "active" ? product.status !== "archived" : product.status === filter)) && `${product.name} ${product.sku}`.toLowerCase().includes(query));
    $("product-list").innerHTML = items.length ? items.map((product) => `<button class="product-row ${product.id === state.selectedId ? "selected" : ""}" data-id="${esc(product.id)}" type="button"><img src="${image(product)}" alt=""><span><strong>${esc(product.name)}</strong><small>${esc(product.sku)} · ${formatPrice(product.price)}</small></span><span class="status ${product.status}">${esc(product.status)}</span></button>`).join("") : `<div class="empty-list">No products match this filter.</div>`;
    document.querySelectorAll(".product-row").forEach((button) => button.addEventListener("click", () => openEditor(button.dataset.id)));
    $("stat-total").textContent = state.products.length; $("stat-published").textContent = state.products.filter((p) => p.status === "published").length; $("stat-drafts").textContent = state.products.filter((p) => p.status === "draft").length; $("stat-low").textContent = state.products.filter((p) => p.status !== "archived" && p.inventory < 5).length;
    $("store-preview").innerHTML = state.products.filter((p) => p.status === "published").map((p) => `<article class="preview-card"><img src="${image(p)}" alt="${esc(p.name)}"><div><strong>${esc(p.name)}</strong><p>${formatPrice(p.price)} · ${p.inventory > 0 ? `${p.inventory} in stock` : "Out of stock"}</p></div></article>`).join("") || `<div class="empty-list">Published products will appear here.</div>`;
  }
  function openEditor(id = null) { state.selectedId = id; const product = state.products.find((item) => item.id === id); $("editor-empty").classList.add("hidden"); $("product-form").classList.remove("hidden"); $("editor-title").textContent = product ? "Edit product" : "New product"; $("archive-product").classList.toggle("hidden", !product); $("name").value = product?.name || ""; $("sku").value = product?.sku || ""; $("description").value = product?.description || ""; $("price").value = product?.price ?? ""; $("inventory").value = product?.inventory ?? ""; $("category").value = product?.category || ""; $("published").checked = product?.status === "published"; $("featured").checked = product?.featured === true; state.images = [...(product?.images || [])]; renderImages(); render(); }
  function closeEditor() { state.selectedId = null; $("product-form").classList.add("hidden"); $("editor-empty").classList.remove("hidden"); render(); }
  function renderImages() { $("image-list").innerHTML = state.images.map((src) => `<img src="${imageSrc(src)}" alt="Product image">`).join(""); }
  $("new-product").addEventListener("click", () => openEditor()); $("empty-new-product").addEventListener("click", () => openEditor()); $("close-editor").addEventListener("click", closeEditor); $("cancel-edit").addEventListener("click", closeEditor); $("product-search").addEventListener("input", render); $("status-filter").addEventListener("change", render);
  $("images").addEventListener("change", () => { Array.from($("images").files || []).slice(0, 8 - state.images.length).forEach((file) => { const reader = new FileReader(); reader.addEventListener("load", () => { state.images.push({ src: reader.result, fileName: file.name, mimeType: file.type }); renderImages(); }); reader.readAsDataURL(file); }); });
  $("product-form").addEventListener("submit", async (event) => { event.preventDefault(); if (!state.images.length) { toast("Add at least one product image."); return; } const current = state.products.find((item) => item.id === state.selectedId); const images = []; for (const item of state.images) { if (item.publicToken || item.url) images.push(item); else if (window.SkaiCloudModuleBridge) images.push(await window.SkaiCloudModuleBridge.upload(item.fileName, item.mimeType, String(item.src).split(",")[1])); else images.push(item.src); } const product = { id: current?.id || crypto.randomUUID(), name: $("name").value.trim(), sku: $("sku").value.trim(), description: $("description").value.trim(), price: Number($("price").value), inventory: Math.max(0, Number($("inventory").value)), category: $("category").value.trim(), images, featured: $("featured").checked, status: $("published").checked ? "published" : "draft", updatedAt: new Date().toISOString() }; try { await saveProduct(product, current); state.products = current ? state.products.map((item) => item.id === current.id ? product : item) : [product, ...state.products]; saved(); toast(product.status === "published" ? "Product published." : "Draft saved."); closeEditor(); } catch (error) { toast(error.message); } });
  $("archive-product").addEventListener("click", async () => { const current = state.products.find((item) => item.id === state.selectedId); try { if (window.SkaiCloudModuleBridge) await window.SkaiCloudModuleBridge.update("products", current.id, { ...current, id: undefined, status: undefined }, false); state.products = state.products.map((item) => item.id === state.selectedId ? { ...item, status: "archived", updatedAt: new Date().toISOString() } : item); if (!window.SkaiCloudModuleBridge) localStorage.setItem(KEY, JSON.stringify(state.products)); saved(); toast("Product archived."); closeEditor(); } catch (error) { toast(error.message); } });
  (async () => { try { state.products = await load(); } catch (error) { toast(error.message); state.products = loadLocal(); } state.loading = false; render(); })();
})();
