(() => {
  const KEY = "skaicloud.commerce_marketplace.products";
  const products = (() => { try { return JSON.parse(localStorage.getItem(KEY) || "[]"); } catch { return []; } })().filter((product) => product.status === "published");
  const state = { query: "", category: "All", sort: "featured" };
  const $ = (id) => document.getElementById(id);
  const esc = (value) => String(value ?? "").replace(/[&<>\"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[char]));
  const image = (product) => product.images?.[0] || "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='300'%3E%3Crect width='100%25' height='100%25' fill='%23e2e8f0'/%3E%3C/svg%3E";
  const price = (value) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value) || 0);
  function render() { let items = products.filter((product) => (state.category === "All" || product.category === state.category) && `${product.name} ${product.description} ${product.sku}`.toLowerCase().includes(state.query)); items = [...items].sort((a, b) => state.sort === "price-low" ? a.price - b.price : state.sort === "price-high" ? b.price - a.price : state.sort === "newest" ? b.updatedAt.localeCompare(a.updatedAt) : Number(b.featured) - Number(a.featured)); $("catalog-count").textContent = `${items.length} product${items.length === 1 ? "" : "s"}`; $("catalog-grid").innerHTML = items.length ? items.map((product) => `<article class="catalog-card" data-id="${esc(product.id)}"><img src="${image(product)}" alt="${esc(product.name)}"><div><p class="eyebrow">${esc(product.category)}</p><h2>${esc(product.name)}</h2><strong>${price(product.price)}</strong><p>${product.inventory > 0 ? `${product.inventory} available` : "Out of stock"}</p></div></article>`).join("") : `<div class="empty-list">No published products found.</div>`; document.querySelectorAll(".catalog-card").forEach((card) => card.addEventListener("click", () => openDetail(card.dataset.id))); }
  function renderCategories() { const categories = ["All", ...new Set(products.map((product) => product.category).filter(Boolean))]; $("catalog-categories").innerHTML = categories.map((category) => `<button class="category-button ${category === state.category ? "active" : ""}" type="button">${esc(category)}</button>`).join(""); document.querySelectorAll(".category-button").forEach((button) => button.addEventListener("click", () => { state.category = button.textContent; renderCategories(); render(); })); }
  function openDetail(id) { const product = products.find((item) => item.id === id); if (!product) return; $("detail-images").innerHTML = (product.images || []).map((src) => `<img src="${src}" alt="${esc(product.name)}">`).join(""); $("detail-category").textContent = product.category; $("detail-name").textContent = product.name; $("detail-price").textContent = price(product.price); $("detail-description").textContent = product.description; $("detail-sku").textContent = `SKU ${product.sku}`; $("detail-stock").textContent = product.inventory > 0 ? `${product.inventory} in stock` : "Out of stock"; $("product-detail").classList.remove("hidden"); $("product-detail").setAttribute("aria-hidden", "false"); }
  function closeDetail() { $("product-detail").classList.add("hidden"); $("product-detail").setAttribute("aria-hidden", "true"); }
  $("catalog-search").addEventListener("input", (event) => { state.query = event.target.value.toLowerCase(); render(); }); $("catalog-sort").addEventListener("change", (event) => { state.sort = event.target.value; render(); }); $("detail-close").addEventListener("click", closeDetail); $("detail-backdrop").addEventListener("click", closeDetail); renderCategories(); render();
})();
