(() => {
  const KEY = "skaicloud.commerce_marketplace.products";
  let products = [];
  const state = { query: "", category: "All", sort: "featured", cart: [], selectedId: null };
  const $ = (id) => document.getElementById(id);
  const esc = (value) => String(value ?? "").replace(/[&<>\"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[char]));
  const image = (product) => { const value = product.images?.[0]; return typeof value === "string" ? value : value?.url || value?.src || "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='300'%3E%3Crect width='100%25' height='100%25' fill='%23e2e8f0'/%3E%3C/svg%3E"; };
  const price = (value) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value) || 0);
  function render() { let items = products.filter((product) => (state.category === "All" || product.category === state.category) && `${product.name} ${product.description} ${product.sku}`.toLowerCase().includes(state.query)); items = [...items].sort((a, b) => state.sort === "price-low" ? a.price - b.price : state.sort === "price-high" ? b.price - a.price : state.sort === "newest" ? b.updatedAt.localeCompare(a.updatedAt) : Number(b.featured) - Number(a.featured)); $("catalog-count").textContent = `${items.length} product${items.length === 1 ? "" : "s"}`; $("catalog-grid").innerHTML = items.length ? items.map((product) => `<article class="catalog-card" data-id="${esc(product.id)}"><img src="${image(product)}" alt="${esc(product.name)}"><div><p class="eyebrow">${esc(product.category)}</p><h2>${esc(product.name)}</h2><strong>${price(product.price)}</strong><p>${product.inventory > 0 ? `${product.inventory} available` : "Out of stock"}</p></div></article>`).join("") : `<div class="empty-list">No published products found.</div>`; document.querySelectorAll(".catalog-card").forEach((card) => card.addEventListener("click", () => openDetail(card.dataset.id))); }
  function renderCategories() { const categories = ["All", ...new Set(products.map((product) => product.category).filter(Boolean))]; $("catalog-categories").innerHTML = categories.map((category) => `<button class="category-button ${category === state.category ? "active" : ""}" type="button">${esc(category)}</button>`).join(""); document.querySelectorAll(".category-button").forEach((button) => button.addEventListener("click", () => { state.category = button.textContent; renderCategories(); render(); })); }
  function openDetail(id) { const product = products.find((item) => item.id === id); if (!product) return; state.selectedId = id; $("detail-images").innerHTML = (product.images || []).map((src) => `<img src="${imageSrc(src)}" alt="${esc(product.name)}">`).join(""); $("detail-category").textContent = product.category; $("detail-name").textContent = product.name; $("detail-price").textContent = price(product.price); $("detail-description").textContent = product.description; $("detail-sku").textContent = `SKU ${product.sku}`; $("detail-stock").textContent = product.inventory > 0 ? `${product.inventory} in stock` : "Out of stock"; $("detail-add").disabled = product.inventory < 1; $("detail-buy").disabled = product.inventory < 1; $("product-detail").classList.remove("hidden"); $("product-detail").setAttribute("aria-hidden", "false"); }
  function imageSrc(value) { return typeof value === "string" ? value : value?.url || value?.src || ""; }
  function renderCart() { $("cart-count").textContent = state.cart.reduce((sum, item) => sum + item.quantity, 0); $("cart-total").textContent = price(state.cart.reduce((sum, item) => sum + Number(item.product.price) * item.quantity, 0)); $("cart-items").innerHTML = state.cart.length ? state.cart.map((item) => `<div class="cart-item"><span><strong>${esc(item.product.name)}</strong><small>${item.quantity} Ã— ${price(item.product.price)}</small></span><button class="icon-button cart-remove" type="button" data-id="${esc(item.product.id)}" aria-label="Remove ${esc(item.product.name)}">Ã—</button></div>`).join("") : `<p class="empty-list">Your cart is empty.</p>`; document.querySelectorAll(".cart-remove").forEach((button) => button.addEventListener("click", () => { state.cart = state.cart.filter((item) => item.product.id !== button.dataset.id); renderCart(); })); $("cart-checkout").disabled = !state.cart.length; }
  function addToCart(id, goToCart = false) { const product = products.find((item) => item.id === id); if (!product || product.inventory < 1) return; const current = state.cart.find((item) => item.product.id === id); if (current) current.quantity = Math.min(current.quantity + 1, product.inventory); else state.cart.push({ product, quantity: 1 }); renderCart(); if (goToCart) { closeDetail(); $("cart-panel").classList.remove("hidden"); $("cart-panel").setAttribute("aria-hidden", "false"); } }
  async function checkout() { if (!state.cart.length) return; $("cart-status").textContent = "Starting secure checkout..."; $("cart-checkout").disabled = true; try { const response = await fetch("/api/module-runtime/commerce_marketplace/checkout", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items: state.cart.map((item) => ({ productKey: item.product.id, quantity: item.quantity })) }) }); const payload = await response.json(); if (!response.ok || !payload.url) throw new Error(payload.error || "Checkout is unavailable."); window.location.assign(payload.url); } catch (error) { $("cart-status").textContent = error.message; $("cart-checkout").disabled = false; } }
  function closeDetail() { $("product-detail").classList.add("hidden"); $("product-detail").setAttribute("aria-hidden", "true"); }
  $("catalog-search").addEventListener("input", (event) => { state.query = event.target.value.toLowerCase(); render(); }); $("catalog-sort").addEventListener("change", (event) => { state.sort = event.target.value; render(); }); $("detail-close").addEventListener("click", closeDetail); $("detail-backdrop").addEventListener("click", closeDetail); $("detail-add").addEventListener("click", () => addToCart(state.selectedId, true)); $("detail-buy").addEventListener("click", () => addToCart(state.selectedId, true)); $("cart-open").addEventListener("click", () => { renderCart(); $("cart-panel").classList.remove("hidden"); $("cart-panel").setAttribute("aria-hidden", "false"); }); $("cart-close").addEventListener("click", () => { $("cart-panel").classList.add("hidden"); $("cart-panel").setAttribute("aria-hidden", "true"); }); $("cart-checkout").addEventListener("click", checkout);
  (async () => { try { if (window.SkaiCloudModuleBridge) { const result = await window.SkaiCloudModuleBridge.list("products", 5000, true); products = (result.records || []).filter((record) => record.published).map((record) => ({ ...record.data, id: record.recordKey, status: "published" })); } else { products = (() => { try { return JSON.parse(localStorage.getItem(KEY) || "[]"); } catch { return []; } })().filter((product) => product.status === "published"); } renderCategories(); render(); renderCart(); } catch { products = []; renderCategories(); render(); renderCart(); } })();
})();
